verifyDepsBeforeRun: install
minimumReleaseAgeExclude:
  - "@oxc-parser/*"
  - "@oxc-project/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"
  - "@oxlint/*"
  - "@rolldown/*"
  - "@tsdown/*"
  - "@vitejs/devtools"
  - "@vitest/*"
  - "@voidzero-dev/*"
  - oxc-parser
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rolldown
  - tsdown
  - vite
  - vite-plus
  - vitest
allowBuilds:
  better-sqlite3: false
  esbuild: false
  sharp: false
  vue-demi: false
  workerd: false
overrides:
  esbuild: 0.28.0
  vite@*: "catalog:"
packages:
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c
  vite-plus: 0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
